name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Playwright Tests
        run: npx playwright test --reporter=html

      - name: Debug Directory Structure
        run: ls -R  # Lists all files and directories

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        with:
          name: playwright Report
          path: playwright-report/

  myjob:
    runs-on: Self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: Anshulpostman/playwrightautomation
          ref: main
          token: ${{ secrets.PAT_TOKEN }}  # Correct token reference

      # name: Run Playwright Tests
       # run: | 
       #  npm install
       #   npx playwright install
       #  npx playwright test  # This line is now commented out and should not run
